# Generated by OpsClaude — devopsteam (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "devopsteam_bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name        = "${var.project_name}-${var.environment}-bucket"
  environment        = var.environment
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team" = "devopsteam"
    "managed-by" = "opsclaude"
  })
}
