# Generated by OpsClaude — devopsteam (dev)

output "bucket_id" {
  description = "ID of the S3 bucket"
  value       = module.devopsteam_bucket.id
}

output "bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = module.devopsteam_bucket.arn
}

output "bucket_name" {
  description = "Name of the S3 bucket"
  value       = module.devopsteam_bucket.bucket_name
}
