# Generated by OpsClaude — data-backup (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "data_backup_bucket" {
  source = "../../modules/s3-bucket"

  bucket_name        = "engineering-data-backup-dev-${random_string.bucket_suffix.result}"
  environment        = var.environment
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team"       = "engineering"
    "managed-by" = "opsclaude"
  })
}

resource "random_string" "bucket_suffix" {
  length  = 8
  special = false
  upper   = false
}
