# Generated by OpsClaude — data-backup (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "data_backup_bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name = "data-backup"
  environment = var.environment
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team" = "engineering"
    "managed-by" = "opsclaude"
  })
}
