# Generated by OpsClaude — data-backup (dev)

output "data_backup_bucket_id" {
  description = "ID of the data_backup_bucket resource"
  value       = module.data_backup_bucket.id
}

output "data_backup_bucket_arn" {
  description = "ARN of the data_backup_bucket resource"
  value       = module.data_backup_bucket.arn
}

output "data_backup_bucket_name" {
  description = "Name of the data_backup_bucket resource"
  value       = module.data_backup_bucket.bucket_name
}
