# Generated by OpsClaude — e2e-read-test (dev)

terraform {
  backend "s3" {
    bucket         = "garda-terraform-state"
    key            = "dev/e2e-read-test/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
  }
}
