# Generated by OpsClaude — data-processor (dev)

terraform {
  backend "s3" {
    bucket         = "garda-terraform-state"
    key            = "dev/data-processor/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
  }
}
