# Generated by OpsClaude — data-processor (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "data-processor" {
  source = "../../../modules/lambda-function"

  function_name = "data-processor"
  runtime       = "python3.12"
  memory_size   = 256
  timeout       = 30
  handler       = "lambda_function.lambda_handler"
  environment   = var.environment

  tags = merge(var.default_tags, {
    "team"       = "backend"
    "managed-by" = "opsclaude"
  })
}
