# Generated by OpsClaude — data-processor (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "data_processor_lambda" {
  source = "../../../modules/lambda-function"

  function_name = "data-processor-lambda"
  runtime = "python3.12"
  memory_size = 256
  timeout = 30
  environment = "dev"

  tags = merge(var.default_tags, {
    "team" = "backend"
    "managed-by" = "opsclaude"
  })
}
