# Generated by OpsClaude — data-processor (dev)

output "data_processor_lambda_function_name" {
  description = "Name of the Lambda function"
  value       = module.data_processor_lambda.function_name
}

output "data_processor_lambda_function_arn" {
  description = "ARN of the Lambda function"
  value       = module.data_processor_lambda.function_arn
}

output "data_processor_lambda_role_arn" {
  description = "ARN of the Lambda IAM role"
  value       = module.data_processor_lambda.role_arn
}
