# Generated by OpsClaude — data-processor (dev)

output "function_name" {
  description = "Name of the Lambda function"
  value       = module.data-processor.function_name
}

output "function_arn" {
  description = "ARN of the Lambda function"
  value       = module.data-processor.function_arn
}

output "role_arn" {
  description = "ARN of the Lambda execution role"
  value       = module.data-processor.role_arn
}
