# Generated by OpsClaude — s3-test-slack (dev)

terraform {
  backend "s3" {
    bucket         = "garda-terraform-state"
    key            = "dev/s3-test-slack/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
  }
}
