# Generated by OpsClaude — s3-test-slack (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "s3_bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name        = "s3-test-slack"
  environment        = var.environment
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team"       = "devops"
    "managed-by" = "opsclaude"
  })
}
