# Generated by OpsClaude — s3-test-slack (dev)

output "bucket_id" {
  description = "ID of the S3 bucket"
  value       = module.s3_bucket.id
}

output "bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = module.s3_bucket.arn
}

output "bucket_name" {
  description = "Name of the S3 bucket"
  value       = module.s3_bucket.bucket_name
}
