# Generated by OpsClaude — s3-test-slack (dev)

output "s3_bucket_id" {
  description = "ID of the s3_bucket resource"
  value       = module.s3_bucket.id
}

output "s3_bucket_arn" {
  description = "ARN of the s3_bucket resource"
  value       = module.s3_bucket.arn
}

output "s3_bucket_name" {
  description = "Name of the s3_bucket resource"
  value       = module.s3_bucket.bucket_name
}
