# Generated by OpsClaude — e2e-test-bucket (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "e2e_test_bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name        = "${var.project_name}-${var.environment}-bucket"
  environment        = var.environment
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team"       = "qa"
    "managed-by" = "opsclaude"
  })
}
