# Generated by OpsClaude — e2e-test-bucket (dev)

output "bucket_id" {
  description = "ID of the S3 bucket"
  value       = module.e2e_test_bucket.id
}

output "bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = module.e2e_test_bucket.arn
}

output "bucket_name" {
  description = "Name of the S3 bucket"
  value       = module.e2e_test_bucket.bucket_name
}
