# Generated by OpsClaude — e2e-test-bucket (dev)

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "dev"
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "e2e-test-bucket"
}

variable "default_tags" {
  description = "Default tags applied to all resources"
  type        = map(string)
  default = {
    Environment = "dev"
    Project     = "e2e-test-bucket"
    ManagedBy   = "terraform"
    CreatedBy   = "opsclaude"
    team = "qa"
    managed-by = "opsclaude"
  }
}
