# Generated by OpsClaude — tests3 (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "tests3_bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name = "tests3"
  environment = "dev"
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team" = "devops"
    "managed-by" = "opsclaude"
  })
}
