# Generated by OpsClaude — tests3 (dev)

output "tests3_bucket_id" {
  description = "ID of the tests3_bucket resource"
  value       = module.tests3_bucket.id
}

output "tests3_bucket_arn" {
  description = "ARN of the tests3_bucket resource"
  value       = module.tests3_bucket.arn
}

output "tests3_bucket_name" {
  description = "Name of the tests3_bucket resource"
  value       = module.tests3_bucket.bucket_name
}
