# Generated by OpsClaude — api-cache (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "dynamodb-table" {
  source = "./modules/dynamodb-table"

  table_name = "api-cache"
  hash_key = "cache_key"
  billing_mode = "PAY_PER_REQUEST"

  tags = merge(var.default_tags, {
    "team" = "backend"
    "managed-by" = "opsclaude"
  })
}

