# Generated by OpsClaude — api-cache (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "api-cache" {
  source = "../../../modules/dynamodb-table"

  table_name = "api-cache-dev"
  hash_key = "cache_key"
  billing_mode = "PAY_PER_REQUEST"
  environment = "dev"

  tags = merge(var.default_tags, {
    "team" = "devops"
    "managed-by" = "opsclaude"
  })
}
