# Generated by OpsClaude — api-cache (dev)

output "table_name" {
  description = "Name of the DynamoDB table"
  value       = module.api-cache.table_name
}

output "table_arn" {
  description = "ARN of the DynamoDB table"
  value       = module.api-cache.table_arn
}
