# Generated by OpsClaude — upload-processor (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "upload_processor_lambda" {
  source = "../../../modules/lambda-function"

  function_name = "upload-processor"
  runtime       = "python3.12"
  memory_size   = 256
  timeout       = 30
  environment   = var.environment

  tags = var.default_tags
}
