# Generated by OpsClaude — upload-processor (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "lambda-function" {
  source = "../../../modules/lambda-function"

  runtime = "python3.12"
  memory_size = 256
  timeout = 30
  handler = "handler.handler"

  tags = merge(var.default_tags, {
    "team" = "backend"
    "managed-by" = "opsclaude"
  })
}


# CI trigger
