# Generated by OpsClaude — upload-processor (dev)

output "lambda_function_name" {
  description = "Name of the Lambda function"
  value       = module.upload_processor_lambda.function_name
}

output "lambda_function_arn" {
  description = "ARN of the Lambda function"
  value       = module.upload_processor_lambda.function_arn
}

output "lambda_role_arn" {
  description = "ARN of the Lambda execution role"
  value       = module.upload_processor_lambda.role_arn
}
