# Generated by OpsClaude — upload-processor (dev)

output "upload-processor-lambda_function_name" {
  description = "Function name of the upload-processor Lambda"
  value       = module.upload-processor-lambda.function_name
}

output "upload-processor-lambda_function_arn" {
  description = "ARN of the upload-processor Lambda"
  value       = module.upload-processor-lambda.function_arn
}

output "upload-processor-lambda_role_arn" {
  description = "IAM role ARN of the upload-processor Lambda"
  value       = module.upload-processor-lambda.role_arn
}

