# Generated by OpsClaude — upload-processor (dev)

output "upload_processor_function_name" {
  description = "Name of the Lambda function"
  value       = module.upload-processor-lambda.function_name
}

output "upload_processor_function_arn" {
  description = "ARN of the Lambda function"
  value       = module.upload-processor-lambda.function_arn
}

output "upload_processor_role_arn" {
  description = "ARN of the Lambda execution role"
  value       = module.upload-processor-lambda.role_arn
}
