# Generated by OpsClaude — test-data (dev)

output "bucket_id" {
  description = "ID of the S3 bucket"
  value       = module.test-data-bucket.id
}

output "bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = module.test-data-bucket.arn
}

output "bucket_name" {
  description = "Name of the S3 bucket"
  value       = module.test-data-bucket.bucket_name
}
