# Generated by OpsClaude — testLambda (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "lambda_function" {
  source = "../../../modules/lambda-function"

  function_name = "testLambda"
  handler = "lambda_function.lambda_handler"
  memory_size = 256
  runtime = "python3.12"
  timeout = 30
  environment = "dev"

  tags = merge(var.default_tags, {
    "team" = "devops"
    "managed-by" = "opsclaude"
  })
}

