# Generated by OpsClaude — testLambda (dev)

output "function_name" {
  description = "Name of the Lambda function"
  value       = module.lambda_function.function_name
}

output "function_arn" {
  description = "ARN of the Lambda function"
  value       = module.lambda_function.function_arn
}

output "role_arn" {
  description = "ARN of the Lambda execution role"
  value       = module.lambda_function.role_arn
}

