# Generated by OpsClaude — cache-service (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "cache_sessions_table" {
  source = "../../../modules/dynamodb-table"

  table_name = "cache-service-sessions-dev"
  hash_key = "session_id"
  billing_mode = "PAY_PER_REQUEST"
  environment = "dev"

  tags = merge(var.default_tags, {
    "team" = "backend"
    "managed-by" = "opsclaude"
  })
}

