# Generated by OpsClaude — cache-service (dev)

output "sessions_table_name" {
  description = "Name of the DynamoDB table"
  value       = module.sessions_table.table_name
}

output "sessions_table_arn" {
  description = "ARN of the DynamoDB table"
  value       = module.sessions_table.table_arn
}
