# Generated by OpsClaude — cache-service (dev)

output "cache_sessions_table_table_name" {
  description = "Table name of the cache_sessions_table DynamoDB table"
  value       = module.cache_sessions_table.table_name
}

output "cache_sessions_table_table_arn" {
  description = "ARN of the cache_sessions_table DynamoDB table"
  value       = module.cache_sessions_table.table_arn
}

