# Generated by OpsClaude — cache-service (dev)

output "cache_sessions_table_name" {
  description = "Name of the DynamoDB table"
  value       = module.cache_sessions_table.table_name
}

output "cache_sessions_table_arn" {
  description = "ARN of the DynamoDB table"
  value       = module.cache_sessions_table.table_arn
}
