# Generated by OpsClaude — backups (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "backups" {
  source = "../../../modules/s3-bucket"

  bucket_name        = "${var.project_name}-${var.environment}-backups"
  environment        = var.environment
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team" = "devops"
    "managed-by" = "opsclaude"
  })
}

