# Generated by OpsClaude — backups (dev)

output "backups_id" {
  description = "ID of the backups S3 bucket"
  value       = module.backups.id
}

output "backups_arn" {
  description = "ARN of the backups S3 bucket"
  value       = module.backups.arn
}

output "backups_bucket_name" {
  description = "Name of the backups S3 bucket"
  value       = module.backups.bucket_name
}

