# Generated by OpsClaude — slack-test (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "slack-test-bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name = "slack-test-dev"
  environment = var.environment
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team" = "platform"
    "managed-by" = "opsclaude"
  })
}
