# Generated by OpsClaude — slack-test (dev)

output "slack-test-bucket_id" {
  description = "ID of the slack-test-bucket resource"
  value       = module.slack-test-bucket.id
}

output "slack-test-bucket_arn" {
  description = "ARN of the slack-test-bucket resource"
  value       = module.slack-test-bucket.arn
}

output "slack-test-bucket_name" {
  description = "Name of the slack-test-bucket resource"
  value       = module.slack-test-bucket.bucket_name
}
