# Generated by OpsClaude — slack-test (dev)

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "dev"
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "slack-test"
}

variable "default_tags" {
  description = "Default tags applied to all resources"
  type        = map(string)
  default = {
    Environment = "dev"
    Project     = "slack-test"
    ManagedBy   = "terraform"
    CreatedBy   = "opsclaude"
    team = "platform"
    "managed-by" = "opsclaude"
  }
}
