# Generated by OpsClaude — pr2-bucket (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "pr2-bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name = "pr2-bucket"
  environment = "dev"
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team" = "sa-team"
    "managed-by" = "opsclaude"
  })
}
