# Generated by OpsClaude — pr2-bucket (dev)

output "pr2_bucket_id" {
  description = "ID of the pr2-bucket S3 bucket"
  value       = module.pr2-bucket.id
}

output "pr2_bucket_arn" {
  description = "ARN of the pr2-bucket S3 bucket"
  value       = module.pr2-bucket.arn
}

output "pr2_bucket_name" {
  description = "Name of the pr2-bucket S3 bucket"
  value       = module.pr2-bucket.bucket_name
}
