# Generated by OpsClaude — pr2-bucket (dev)

output "bucket_id" {
  description = "ID of the S3 bucket"
  value       = module.pr2-bucket.id
}

output "bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = module.pr2-bucket.arn
}

output "bucket_name" {
  description = "Name of the S3 bucket"
  value       = module.pr2-bucket.bucket_name
}
