# Generated by OpsClaude — pr2-bucket (dev)

output "pr2-bucket_id" {
  description = "ID of the pr2-bucket resource"
  value       = module.pr2-bucket.id
}

output "pr2-bucket_arn" {
  description = "ARN of the pr2-bucket resource"
  value       = module.pr2-bucket.arn
}

output "pr2-bucket_bucket_name" {
  description = "Bucket name of the pr2-bucket resource"
  value       = module.pr2-bucket.bucket_name
}
