# Generated by OpsClaude — app-logs (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "app-logs" {
  source = "../../../modules/s3-bucket"

  bucket_name         = "app-logs"
  environment         = "dev"
  versioning_enabled  = true
  encryption_enabled  = true

  tags = merge(var.default_tags, {
    "team"       = "platform-team"
    "managed-by" = "opsclaude"
  })
}
