# Generated by OpsClaude — app-logs (dev)
# Do not edit manually. Changes will be overwritten on next generation.

# Random ID for unique bucket naming
resource "random_id" "suffix" {
  byte_length = 4
}

module "s3_bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name = "app-logs-dev-${random_id.suffix.hex}"
  environment = "dev"
  versioning_enabled = true
  encryption_enabled = true
  tags = merge(var.default_tags, {
    "Name" = "app-logs"
    "team" = "platform-team"
    "managed-by" = "opsclaude"
  })
}
