# Generated by OpsClaude — app-logs (dev)

output "bucket_id" {
  description = "ID of the S3 bucket"
  value       = module.app-logs-bucket.id
}

output "bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = module.app-logs-bucket.arn
}

output "bucket_name" {
  description = "Name of the S3 bucket"
  value       = module.app-logs-bucket.bucket_name
}
