# Generated by OpsClaude — app-logs (dev)

output "app_logs_bucket_id" {
  description = "ID of the app-logs bucket"
  value       = module.app-logs-bucket.id
}

output "app_logs_bucket_arn" {
  description = "ARN of the app-logs bucket"
  value       = module.app-logs-bucket.arn
}

output "app_logs_bucket_name" {
  description = "Name of the app-logs bucket"
  value       = module.app-logs-bucket.bucket_name
}
