# Generated by OpsClaude — test (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "test-bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name        = "test-bucket-dev-${random_id.bucket_suffix.hex}"
  environment        = "dev"
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team"       = "engineeringteam"
    "managed-by" = "opsclaude"
  })
}

resource "random_id" "bucket_suffix" {
  byte_length = 4
}
