# Generated by OpsClaude — test (dev)

output "test_bucket_id" {
  description = "ID of the test-bucket resource"
  value       = module.test-bucket.id
}

output "test_bucket_arn" {
  description = "ARN of the test-bucket resource"
  value       = module.test-bucket.arn
}

output "test_bucket_name" {
  description = "Name of the test-bucket resource"
  value       = module.test-bucket.bucket_name
}
