# Generated by OpsClaude — session-store (dev)

terraform {
  backend "s3" {
    bucket         = "hechmi-terraform-state"
    key            = "dev/session-store/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
  }
}
