# Generated by OpsClaude — session-store (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "user-sessions-table" {
  source = "../../modules/dynamodb-table"

  table_name   = "user-sessions-dev"
  hash_key     = "session_id"
  billing_mode = "PAY_PER_REQUEST"
  environment  = var.environment

  tags = merge(var.default_tags, {
    "team"       = "backend"
    "managed-by" = "opsclaude"
  })
}
