# Generated by OpsClaude — session-store (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "user_sessions_table" {
  source = "../../../modules/dynamodb-table"

  table_name    = "${var.project_name}-${var.environment}-user-sessions"
  hash_key      = "session_id"
  range_key     = ""
  billing_mode  = "PAY_PER_REQUEST"
  environment   = var.environment
  
  tags = merge(var.default_tags, {
    "team"       = "backend"
    "managed-by" = "opsclaude"
  })
}
