# Generated by OpsClaude — session-store (dev)

output "table_name" {
  description = "Name of the DynamoDB table"
  value       = module.user-sessions-table.table_name
}

output "table_arn" {
  description = "ARN of the DynamoDB table"
  value       = module.user-sessions-table.table_arn
}
