# Generated by OpsClaude — session-store (dev)

output "table_name" {
  description = "Name of the DynamoDB sessions table"
  value       = module.user_sessions_table.table_name
}

output "table_arn" {
  description = "ARN of the DynamoDB sessions table"
  value       = module.user_sessions_table.table_arn
}
