# Generated by OpsClaude — table1 (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "table1" {
  source = "../../../modules/dynamodb-table"

  table_name = "table1"
  hash_key = "user_id"
  billing_mode = "PAY_PER_REQUEST"
  environment = var.environment

  tags = merge(var.default_tags, {
    "team" = "devops"
    "managed-by" = "opsclaude"
  })
}
