# Generated by OpsClaude — table1 (dev)

output "table_name" {
  description = "Name of the DynamoDB table"
  value       = module.table1.table_name
}

output "table_arn" {
  description = "ARN of the DynamoDB table"
  value       = module.table1.table_arn
}
