# Generated by OpsClaude — thenewbucket (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "thenewbucket" {
  source = "../../../modules/s3-bucket"

  bucket_name         = "thenewbucket"
  environment         = var.environment
  versioning_enabled  = true
  encryption_enabled  = true

  tags = merge(var.default_tags, {
    "team" = "testteam"
    "managed-by" = "opsclaude"
  })
}
