# Generated by OpsClaude — thenewbucket (dev)

output "thenewbucket_id" {
  description = "ID of the thenewbucket resource"
  value       = module.thenewbucket.id
}

output "thenewbucket_arn" {
  description = "ARN of the thenewbucket resource"
  value       = module.thenewbucket.arn
}

output "thenewbucket_bucket_name" {
  description = "Bucket name of the thenewbucket resource"
  value       = module.thenewbucket.bucket_name
}
