# Generated by OpsClaude — playwright-test (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "playwright-test-bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name = "playwright-test-${var.environment}"
  environment = var.environment
  versioning_enabled = true
  encryption_enabled = true

  tags = merge(var.default_tags, {
    "team" = "qa"
    "managed-by" = "opsclaude"
  })
}
