# Generated by OpsClaude — playwright-test (dev)

output "bucket_id" {
  description = "ID of the S3 bucket"
  value       = module.playwright-test-bucket.id
}

output "bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = module.playwright-test-bucket.arn
}

output "bucket_name" {
  description = "Name of the S3 bucket"
  value       = module.playwright-test-bucket.bucket_name
}
