# Generated by OpsClaude — thisProject (dev)
# Do not edit manually. Changes will be overwritten on next generation.

module "s3-bucket" {
  source = "../../../modules/s3-bucket"

  bucket_name = "thisProject"
  versioning_enabled = true
  encryption_enabled = true
  environment = var.environment

  tags = merge(var.default_tags, {
    "team" = "devops"
    "managed-by" = "opsclaude"
  })
}
