# Generated by OpsClaude — thisProject (dev)

output "s3-bucket_id" {
  description = "ID of the s3-bucket resource"
  value       = module.s3-bucket.id
}

output "s3-bucket_arn" {
  description = "ARN of the s3-bucket resource"
  value       = module.s3-bucket.arn
}

output "s3-bucket_name" {
  description = "Name of the s3-bucket resource"
  value       = module.s3-bucket.bucket_name
}
